language: C#

install:
  - wget http://download.opensuse.org/repositories/home:tpokorra:mono/xUbuntu_14.04/Release.key
  - sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/tpokorra:/mono/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/mono-opt.list"
  - sudo apt-key add - < Release.key
  - sudo apt-get update -qq
  - sudo apt-get install NAnt -qq
  - sudo apt-get install mono-opt -qq

script:
  - mono --version
  - mono /usr/lib/NAnt/NAnt.exe
